name: ${PROJECT_CODE}

services:
    svc:
        container_name: coc_back
        image: coc_back:prod
        pull_policy: if_not_present
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${APP_PORT}:5000
        env_file:
            - .env
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://0.0.0.0:5000/api/v1/ || exit 1']
            start_period: 10s
            interval: 30s
            timeout: 2s
            retries: 3

networks:
    default:
        name: ${DOCKER_NETWORK_NAME}
        external: true
