FROM python:3.12

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

# CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "80"]
# CMD uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
CMD ["python3", "-X", "frozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "5001"]